version: '3.1'
services:
  mysql:
    container_name: DouYin-MySQL
    image: 'mysql'
    restart:
      on-failure
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./db/mysql:/var/lib/mysql