version: '3.1'
services:
  mysql:
    container_name: DouYin-MySQL
    image: 'mysql'
    restart:
      on-failure
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./init_mysql.sql:/docker-entrypoint-initdb.d/init_mysql.sql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    container_name: redis
    image: 'redis'
    restart:
      on-failure
    ports:
      - 6379:6379
    volumes:
      - ./db/redis/data:/data
      - ./redis.conf:/redis.conf
    command: 
      redis-server /redis.conf